run1:
	go build -o lab1/lab1 ./lab1/lab1.go 
	go run syspo.go "1"
run2:
	go build -o lab2/lab2 ./lab2/lab2.go 
	go run syspo.go "2"
run3.1:
	go build -o lab3.1/rd ./lab3.1/reader/rd.go 
	go build -o lab3.1/wr ./lab3.1/writer/wr.go 
	go run syspo.go "3.1"